### ISSUE TITLE
Convert to number?

### ISSUE THREAD

**Issue by gaertner-siu** [ggreen86/XLSX-Workbook-Class#79] opened 2023-02-03 19:49 UTC
I need to selectively "convert to number" in particular cells.  Looking at the documentation, SetCellNumberFormat has been deprecated.

Is there a function that can be used to "convert to number" on a cell?

**Comment by ggreen86** [comment] 2023-02-03 22:55
Hello—

You would need to define a format style.  Use the CreateFormatStyle() method to first create a new style.  This new style will allow you to add the font, borders, numeric format, etc. to the style.  Then you can assign the style to any cell that you want.  See the Cell Style section in the documentation for more information.

Greg

From: gaertner-siu ***@***.***>
Sent: Friday, February 3, 2023 2:50 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Convert to number? (Issue #79)


I need to selectively "convert to number" in particular cells. Looking at the documentation, SetCellNumberFormat has been deprecated.

Is there a function that can be used to "convert to number" on a cell?

**Comment by gaertner-siu** [comment] 2023-02-08 16:26
Greg,

Thanks for pointing me to the CreateFormatStyle().  Using that with AddStyleNumericFormat() is working for my use case.  However, I'm having a problem where opening the XLSX file and saving it:

    lnWb = loExcel.OpenXlsxWorkbook(lcFile)
    loExcel.SaveWorkbook(lnWb)

Is removing the header row.  What is causing the header row to be removed?

Thanks,
Chris

**Comment by ggreen86** [comment] 2023-02-11 16:41
Chris

I tried to duplicate the problem and I am not able to.  I created a test spreadsheet with 3 columns and 5 rows with text and values in the cells.  I then opened the spreadsheet with the class and immediately saved it.  The saved version is the same as the original – the header row is not missing.  Are you using the latest version of the class?  If your problem still persists, can you send me the workbook that is causing the problem?  Thank you.

Greg

**Comment by gaertner-siu** [comment] 2023-02-13 15:16
Greg,

I've attached 3 files:  the DBF source file, the #1 Excel version after the following code executes:

    lcTable = 'i:\appdev\icss\billing\bill_xl_file.dbf'
    lcFile = 'i:\appdev\icss\billing\'+DTOC(m.run_date,1)+'_'+ALLTRIM(su_list.desc)+'_bill_entries.xlsx'
    loExcel = NEWOBJECT("VFPxWorkbookXLSX", "C:\CM75\Thor\Thor\Tools\Components\XLSX Workbook\VFPxWorkbookXLSX.vcx")
    lnWb = loExcel.SaveTabletoWorkbook(lcTable, lcFile, .T., .T.)
    RELEASE loExcel

And then the #2 Excel version (with the headers missing) after the following code executes immediately after:

    loExcel = NEWOBJECT("VFPxWorkbookXLSX", "C:\CM75\Thor\Thor\Tools\Components\XLSX Workbook\VFPxWorkbookXLSX.vcx")
    lnWb = loExcel.OpenXlsxWorkbook(lcFile)
    loExcel.SaveWorkbook(lnWb)
    RELEASE loExcel

Thanks,
Chris

**Comment by ggreen86** [comment] 2023-02-13 15:39
Chris--

The attachments are not making it through.  Please try to anduril58 hotmail com  thank you.

Greg

**Comment by ggreen86** [comment] 2023-02-13 16:52
Chris—

Looking at the file, the first row (header) is actually being saved to the copy.  However, the setting frozen split to keep the header at the top is what is causing the issue.  If the Freeze Pane and Split is reset (removed) then the first row appears.  The problem is with the internal setting for the freeze top row – using “frozenSplit” rather than “frozen”.  I am now testing to ensure that this will fix the issue and not create another issue when setting the freeze.

Thank you.

Greg

**Comment by ggreen86** [comment] 2023-02-13 20:12
The issue with the missing row (first row) was due to the freeze row method in creating the initial workbook.  When the workbook was read in, the setting for the freeze row command (split) was causing the row to be masked; the row was still there and not missing but you could not see it due to the split.  This has been fixed now in Release 35.

**Closed by ggreen86** 2023-02-13 20:12 UTC

**Comment by gaertner-siu** [comment] 2023-02-13 20:25
Greg,

I can confirm R35 fixes the issue.

Thanks!
Chris
