### ISSUE TITLE
About SetSheetVisibility

### ISSUE THREAD

**Issue by jhernancanom** [ggreen86/XLSX-Workbook-Class#33] opened 2020-09-13 10:09 UTC
Hi, Greg and friends.
I have found something that I want to share.

When I use **SetSheetVisibility** with 1 to hide a sheet, this doesnot run.

When I use **SetSheetVisibility** with 2 to very-hide a sheet, it does run, yes, but in the resulting XLSX I cannot make it visible, because it doesnt appear in the list (to Show hidden sheets).

If someone could give me some workaround, I'll appreciate.

HERNAN CANO
Systems Analyst

**Comment by ggreen86** [comment] 2020-09-13 23:03
I will look into this and let you know.

Greg

________________________________

**Comment by ggreen86** [comment] 2020-10-05 23:19
Hernan--

I am not able to reproduce a problem with the method SetSheetVisibility().  In the Demo() method I show an example of hiding a sheet using this method.  If I execute the Demo() method and create a spreadsheet and then subsequently open and save-as the workbook, I still retain the visibility setting of the 'List of Values' sheet (hidden).

Please provide sample code to reproduce the behavior you are seeing.  I am currently working/testing the next release and would like to ensure this is not a problem/bug.  Thank you.

Greg

**Comment by jhernancanom** [comment] 2020-10-10 01:42
In "About hidden columns #32" I send you the sample. 
I re-send it to you in this #33 issue.

[CopyToHoja1.zip](https://github.com/ggreen86/XLSX-Workbook-Class/files/5358251/CopyToHoja1.zip)

Thanks, friend.

**Comment by ggreen86** [comment] 2020-10-14 19:55
I found that I was not capturing the hidden column setting in the spreadsheet during opening.  This will be fixed in the next beta release (Release 32 beta 14).

**Closed by ggreen86** 2020-10-14 19:55 UTC

**Comment by jhernancanom** [comment] 2020-10-16 02:53
Fine, Greg.
Thanks.
