### ISSUE TITLE
InsertRow method not saving the footer rows correctly.

### ISSUE THREAD

**Issue by rawilliamsjr** [ggreen86/XLSX-Workbook-Class#108] opened 2024-01-29 20:31 UTC
[Availability_Template.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/14089259/Availability_Template.xlsx)

Using the attached Excel file and issuing this command the last footer row values are missing and the rows merged cells have been unmerged.

goExcel.InsertRow(lnWb, 1, 20, INSERT_BEFORE)

**Comment by ggreen86** [comment] 2024-01-29 21:46
I will look into the problem.  Thank you for submitting the spreadsheet for testing.

**Comment by rawilliamsjr** [comment] 2024-02-05 23:56
Do you have an ETA for this correction? We are in the middle of a large project and this issue is holding us up from completing the project.

**Comment by ggreen86** [comment] 2024-02-12 22:18
Hello--

I have corrected the issue of not retaining the footer and header.  This was actually not caused by the InsertRow method; but rather, I was not saving the these definitions when reading an existing workbook.  I have added the retaining of the header/footer definitions when the open method is used.  This will be in Release 41.

**Closed by ggreen86** 2024-02-12 22:18 UTC
