### ISSUE TITLE
Supporting shared formulas in existing documents

### ISSUE THREAD

**Issue by Starfiresg1** [ggreen86/XLSX-Workbook-Class#59] opened 2021-07-06 13:57 UTC
I'm trying to open a document containing shared formula.
Example excerpt from the sheet.xml:
`<row r="20" x14ac:dyDescent="0.25" customHeight="1" ht="15" spans="1:11">
<c r="A20" s="17">
<v>1</v>
</c>
<c r="B20" s="18"/>
<c r="C20" s="19"/>
<c r="D20" s="19"/>
<c r="E20" s="20"/>
<c r="F20" s="21"/>
<c r="G20" s="22"/>
<c r="H20" s="23" t="str">
<f ref="H20:H36" t="shared" si="0">IF(G20="","",F20*G20)</f>
<v/>
</c>
<c r="I20" s="14"/>
<c r="J20"/>
<c r="K20"/>
</row>`

Initially the formula in H20 to H36 are not recognized in readcellvalueformat. GetChildNodeElement uses STREXTRACT to extract the content of the child nodes. However this works only for tags without extended data: <f>IF(G20="","",F20*G20)</f> would work but <f ref="H20:H36" t="shared" si="0">IF(G20="","",F20*G20)</f> does not, because the opening and closing tags differ.
Due to this the columns contain the wrong data after saving (the shared string with id 0).

I tried working around this but after reading the tag correctly I got stopped in GetCellFormulaFromXML: It tries to seek and store the shared formulas in a cursor "t_shared" that doesn't exist.

I hope this can be supported in the future.

**Comment by ggreen86** [comment] 2021-07-06 14:04
Can you provide me an example spreadsheet that contains the shared formula that you are trying to open?  Thank you.

________________________________
From: Starfiresg1 ***@***.***>
Sent: Tuesday, July 6, 2021 9:57 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Supporting shared formulas in existing documents (#59)


I'm trying to open a document containing shared formula.
Example excerpt from the sheet.xml:
<row r="20" x14ac:dyDescent="0.25" customHeight="1" ht="15" spans="1:11"> <c r="A20" s="17"> <v>1</v> </c> <c r="B20" s="18"/> <c r="C20" s="19"/> <c r="D20" s="19"/> <c r="E20" s="20"/> <c r="F20" s="21"/> <c r="G20" s="22"/> <c r="H20" s="23" t="str"> <f ref="H20:H36" t="shared" si="0">IF(G20="","",F20*G20)</f> <v/> </c> <c r="I20" s="14"/> <c r="J20"/> <c r="K20"/> </row>

Initially the formula in H20 to H36 are not recognized in readcellvalueformat. GetChildNodeElement uses STREXTRACT to extract the content of the child nodes. However this works only for tags without extended data: IF(G20="","",F20G20) would work but IF(G20="","",F20G20) does not, because the opening and closing tags differ.
Due to this the columns contain the wrong data after saving (the shared string with id 0).

I tried working around this but after reading the tag correctly I got stopped in GetCellFormulaFromXML: It tries to seek and store the shared formulas in a cursor "t_shared" that doesn't exist.

I hope this can be supported in the future.

**Comment by Starfiresg1** [comment] 2021-07-07 13:49
Here is an example,
formulas are in H20 to H36

Before.xlsx: File before opening and saving using XLSX-Workbook
After.xlsx: File after opening and saving without any changes (opened using OpenXlsxWorkbookSheet)

The formulas are gone and the first shared string appears instead.

Note: the column/row lines seem to be also missing after saving - but thats a spearate issue.

[Before.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/6777583/Before.xlsx)
[After.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/6777582/After.xlsx)

**Comment by ggreen86** [comment] 2021-07-08 14:10
I have successfully added the code to read the shared formulas and restore back to the workbook on saving.  I still have more regression testing to do to ensure that I have not impacted other reading of spreadsheets without shared formulas.  I don't think I will have a problem here.

I now have to update the GetCellFormula() method to retrieve the formula in the event it is shared; this is partially coded.  Also, I have to debug and find out why I am losing the formatting in reading the spreadsheet.

See the screen-shot of the spreadsheet opened by the class and then resaved to a copy; you can see the formulas are now being retained.  But you can see the cell formatting is lost.

[cid:a4ca5bd6-03b7-46b4-b020-680911426f79]

________________________________

**Comment by ggreen86** [comment] 2021-07-13 14:58
Please see Release 33 beta 10 version.  I have added the support for shared formulas.

**Closed by ggreen86** 2021-07-13 14:58 UTC
