### ISSUE TITLE
Need repair after saving same file with SaveWorkbook function

### ISSUE THREAD

**Issue by Abh7791** [ggreen86/XLSX-Workbook-Class#120] opened 2024-08-07 15:06 UTC
Hi, 
I am testing this with my code but Demo() also having same issue. 
Kindly check attached photo. 
![image](https://github.com/user-attachments/assets/31aea569-7775-47d0-baf4-7b64643dd951)

From what I can gather problem come from SaveWorkbook function only . 
Thanks

**Comment by ggreen86** [comment] 2024-08-08 23:52
Hello—

I just created the ExcelTest.xlsx file from the Demo() method (I am using Release 44) via excelxlsxtest.prg.  I also successfully opened it in Excel 2016 with no errors.  Please send me the ExcelTest.xlsx file that you created and send me the corrected file from Excel as ExcelTest_Fixed.xlsx so that I can see if I can find a problem.

Greg

From: Abh7791 ***@***.***>
Sent: Wednesday, August 7, 2024 11:07 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Need repair after saving same file with SaveWorkbook function (Issue #120)


Hi,
I am testing this with my code but Demo() also having same issue.
Kindly check attached photo.
image.png (view on web)<https://github.com/user-attachments/assets/31aea569-7775-47d0-baf4-7b64643dd951>

From what I can gather problem come from SaveWorkbook function only .
Thanks

**Comment by Abh7791** [comment] 2024-08-11 05:00
Thanks for quick reply .
I have checked again with release 44 and using office 2019 professional plus.
I am attaching both excel files.
[ExcelTest_originaal.xlsx](https://github.com/user-attachments/files/16571625/ExcelTest_originaal.xlsx)
[ExcelTest-Fixed.xlsx](https://github.com/user-attachments/files/16571626/ExcelTest-Fixed.xlsx)

**Comment by ggreen86** [comment] 2024-08-13 21:46
In looking at your original file that was created, you are missing the Image Example sheet being written correctly.  I suspect that you may be missing the file “vfpxbanner.gif” which should be in the same directory as the default directory.  The program “excelxlsxtest.prg” if executed will set the current directory to its execution path; on my system this is:

SET DEFAULT TO "e:\my work\foxpro\projects\workbookxlsx\program demos"
DO excelxlsxtest.prg

You might try the above in VFP by navigating to the directory containing the program “excelxlsxtest.prg” and then executing it.

Greg

**Comment by Abh7791** [comment] 2024-08-17 11:11
I just did another test. 
I created simple xlsx file just one column . 
and saved it again by function SaveWorkbook . 
It giving me same error.

**Comment by Abh7791** [comment] 2024-08-17 11:11
I just did another test. 
I created simple xlsx file just one column . 
and saved it again by function SaveWorkbook . 
It giving me same error.

**Comment by ggreen86** [comment] 2024-08-18 23:58
I would have to have your code in order to be able to understand what you did.  The class does not have a method to create a column; it has a method to assign a value to a cell.  The class does have a method to define a column width.

Right now I am not able to reproduce any error that you are describing.  I have attached the xlsx file that the demo method creates.  Please try to open this file with your version of Excel and if it gives an error, please send me the corrected file that Excel produces.

Thank you.

Greg

**Comment by ggreen86** [comment] 2024-10-03 19:16
**Closing issue.**  No reply from Originator from my last request for more testing.  The problem may be in how Excel 2019 is expecting the file layout.  I have no way to test with Excel 2019 and I cannot reproduce any errors with Excel 2016 that I have installed.

**Closed by ggreen86** 2024-10-03 19:16 UTC
