### ISSUE TITLE
SaveWorkbook changing existing cell styles

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#125] opened 2024-10-03 21:58 UTC
I created a document using VFPXWorkbookXLSX R46. I then edited it, selected row 2, and click "Bad" in the Styles section in the ribbon to apply that style (red text on a pink background):

![image](https://github.com/user-attachments/assets/5c58e5d1-5823-46f1-960a-d1eed83e10d6)

I then used this code to change the value of a cell:

```
loExcel = newobject('VFPXWorkbookXLSX', 'VFPXWorkbookXLSX.vcx')
lnWB   = loExcel.OpenXLSXWorkbook('Renewals.xlsx')
loExcel.SetCellValue(lnWB, 1, 3, 8, 'Testing')
loExcel.SaveWorkbook(lnWB)
```

The row with the Bad style was changed to a black background:

![image](https://github.com/user-attachments/assets/2de5e5ea-d6c4-43f6-b6ea-a726b14aae23)

I've attached the document with the "Bad" row so you can reproduce this.
[Renewals.xlsx](https://github.com/user-attachments/files/17250462/Renewals.xlsx)

**Comment by ggreen86** [comment] 2024-10-04 03:29
The problem is that I am not saving the original styles defined and saved into the workbook when I open it.  I will look into adding this capability for the next release.  BTW -- the next number is actually 45 and not 46 (I missed it...).

**Comment by ggreen86** [comment] 2024-10-07 19:55
This issue is fixed in R45.

**Closed by ggreen86** 2024-10-07 19:55 UTC
